### ISSUE TITLE
Using with Gatsby?

### ISSUE THREAD

**Issue by samuelgoddard** [locomotivemtl/locomotive-scroll#75] opened 2020-01-20 23:18 UTC
Has anyone got a working example of utilising this in Gatsby?

I can get as far as having it working in the layout file but when i change page it de-renders all my child content.

layout.js
```
import React, { useEffect } from "react"
import PropTypes from "prop-types"
import { motion, AnimatePresence } from 'framer-motion'
import locomotiveScroll from "locomotive-scroll"

import Header from "./header"
import Footer from "./footer"

import "../styles/main.css"

const duration = 0.35

const variants = {
  initial: {
    opacity: 0,
  },
  enter: {
    opacity: 1,
    transition: {
      duration: duration,
      delay: duration,
      when: 'beforeChildren',
    },
  },
  exit: {
    opacity: 0,
    transition: {
      duration: duration,
    },
  },
}

const Layout = ({ children, location }) => {
  const scrollRef = React.createRef()
  useEffect(() => {
    const scroll = new locomotiveScroll({
      el: scrollRef.current,
      smooth: true,
    })
  })
  return (
    <>
      <Header />
      <AnimatePresence>
        <motion.main
          key={location.pathname}
          variants={variants}
          initial="initial"
          animate="enter"
          exit="exit"
          ref={scrollRef}
        >
          {children}
          <Footer />
        </motion.main>
      </AnimatePresence>
    </>
  )
}

Layout.propTypes = {
  children: PropTypes.node.isRequired,
}

export default Layout
```

**Comment by antoineboulanger** [comment] 2020-01-22 15:31
Duplicate of #13

**Closed by antoineboulanger** 2020-01-22 15:31 UTC
