### ISSUE TITLE
Usage with React

### ISSUE THREAD

**Issue by ajayns** [locomotivemtl/locomotive-scroll#53] opened 2019-10-23 03:38 UTC
Is there any documentation or things to note while using this library with React or Gatsby? I see that you have a React boilerplate (https://github.com/locomotivemtl/locomotive-react-boilerplate) but it provides no insight into this as it's more of a stripped-down boilerplate.

By testing things my way on Gatsby there seem to be a couple of bugs that I believe could be caused by improper usage. So any ideas on using the library optimally would be appreciated. Far fetched but it'll also be great if you could add locomotive-scroll to the react boilerplate.

**Comment by ajayns** [comment] 2019-10-23 08:36
I'm also noticing issues with Gatsby in particular. I believe this package isn't SSR friendly?

**Comment by ajayns** [comment] 2019-10-23 08:46
The fix I've found for Gatsby for SSR would be to add the following in `gatsby-node.js`:
```
exports.onCreateWebpackConfig = ({ stage, loaders, actions }) => {
  if (stage === 'build-html') {
    actions.setWebpackConfig({
      module: {
        rules: [
          {
            test: /locomotive-scroll/,
            use: loaders.null(),
          },
        ],
      },
    });
  }
};

```

**Comment by adamjw3** [comment] 2019-10-23 10:07
i'

> The fix I've found for Gatsby for SSR would be to add the following in `gatsby-node.js`:
> 
> ```
> exports.onCreateWebpackConfig = ({ stage, loaders, actions }) => {
>   if (stage === 'build-html') {
>     actions.setWebpackConfig({
>       module: {
>         rules: [
>           {
>             test: /locomotive-scroll/,
>             use: loaders.null(),
>           },
>         ],
>       },
>     });
>   }
> };
> ```

i've used the same when using with gatsby

**Comment by antoineboulanger** [comment] 2020-01-22 15:31
Duplicate of #13

**Closed by antoineboulanger** 2020-01-22 15:31 UTC
Labels: duplicate, enhancement
