### ISSUE TITLE
On refresh does not scroll up to top

### ISSUE THREAD

**Issue by Lacika1981** [locomotivemtl/locomotive-scroll#72] opened 2020-01-14 10:12 UTC
Hello 👋

**Describe the bug**
When I refresh the page most of the time the current position is calculated as top of the page. To make it clear. If I scrolled down to half of the page and refresh it then the top of the page will be at the half of the page. I cannot scroll up but I can scroll down having blank section.

**To Reproduce**
Here is my very basic structure

`<div id="loco-scroll">
      <div
        class="one vertical red"
        data-scroll
        data-scroll-speed="0"
        data-scroll-direction="vertical"
      ></div>
      <div
        class="two horizontal green"
        data-scroll
        data-scroll-speed="4"
        data-scroll-direction="horizontal"
      ></div>
      <div
        class="three horizontal blue"
        data-scroll
        data-scroll-speed="2"
        data-scroll-direction="horizontal"
      ></div>
      <div
        class="four horizontal yellow"
        data-scroll
        data-scroll-speed="2"
        data-scroll-direction="horizontal"
      ></div>
      <div
        class="five vertical orange"
        data-scroll
        data-scroll-speed="2"
        data-scroll-direction="vertical"
      ></div>
    </div>
    <script src="js/locomotive-scroll.js"></script>
    <script>
      const scroll = new LocomotiveScroll({
        el: document.querySelector('#loco-scroll'),
        smooth: true,
      });
    </script>`

stylesheet
`#loco-scroll div {
  width: 100vw;
  height: 100vh;
}

.red {
  background-color: red;
}
.green {
  background-color: green;
}
.blue {
  background-color: blue;
}
.yellow {
  background-color: yellow;
}
.orange {
  background-color: orange;
}`

**Expected behavior**
Jump to top of the page

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS Catalin v10.15.2
 - Browser same thing happens in <del>Safari, Firefox,</del> Chrome
 - Version latest

Thank you 👊

Laszlo

**Comment by Lacika1981** [comment] 2020-01-14 10:14
I suspect the width and height property can cause issue but I need them to be full screen.
When I close window and open a new one it renders correctly. Only refresh causes this issue.

**Comment by maximeDore** [comment] 2020-01-31 21:03
I have noticed this issue on Chrome. Firefox seems fine and always starts at the top of the page upon refreshing.

One way to counter this is to add a handler on the `onbeforeunload` event and force the window to go back to top with javascript like so :
`window.onbeforeunload = function () {
    window.scrollTo(0,0);
};`
Weirdly enough, it doesn't seem to work on one of my coworker's computer (Chrome)

**Comment by jarovision** [comment] 2020-02-12 13:56
i am running into the same issue with the plugin and used a similar method to always scroll to the top whenever a page reloads. but i would actually love to see this fixed. 🥇

**Comment by pierredarrieutort** [comment] 2020-02-25 10:12
> I have noticed this issue on Chrome. Firefox seems fine and always starts at the top of the page upon refreshing.
> 
> One way to counter this is to add a handler on the `onbeforeunload` event and force the window to go back to top with javascript like so :
> `window.onbeforeunload = function () { window.scrollTo(0,0); };`
> Weirdly enough, it doesn't seem to work on one of my coworker's computer (Chrome)

Same problem here using the [Locomotive scroll instance method](https://github.com/locomotivemtl/locomotive-scroll/blob/master/README.md#instance-methods) on Chrome (no problem on Firefox).

**Comment by maximeDore** [comment] 2020-02-25 19:21
I have managed to find a working hack for this. Using a setTimeout of only 10ms after initializing Locomotive-scroll to force the window to scroll up seems to be working fine, even with a page transition plugin like Swup.
`setTimeout(function(){
    window.scrollTo(0,0);
}, 10);`
Sadly, having any kind of delay (even as short as 10ms) might cause a slight stutter on page load.

**Comment by podrivo** [comment] 2020-02-27 13:44
I'm having the same issue. `setTimeout()` and `window.onbeforeunload` didn't work.

**Comment by podrivo** [comment] 2020-02-27 13:57
After testing some CSS, I found you need to set `width` and `height` in `html, body` to properly work after refreshing the page.

```
html, body {
   width: 100vw;
   height: 100vh;
}
```

Documentation needs an upgrade!

**Comment by dangelion** [comment] 2020-03-01 10:13
@podrivo Yes, it's working, is this a workaround or is the way the library works? I so this need to be in the documentation

Second, refreshing the page starts from top, but is this the correct behavior. It would be better if refreshing page started from the previous position.

**Comment by podrivo** [comment] 2020-03-01 13:21
@dangelion I'm not sure this is how the lib works, given that I already had a bunch of code in my website. Nonetheless, documentation could provide more examples.

And I agree with you that would be better if refreshing page started from the previous position, but I'm pretty sure this is an intended behavior. We've all been warned on hijacking scrolls.  😅

**Comment by elebumm** [comment] 2020-03-03 00:21
@podrivo's answer didn't work for me. It somehow disabled the scroll altogether. This only seems to happen in Chrome.

**Comment by guyhamilton** [comment] 2020-04-07 22:19
@elebumm - I have the same issue. Funnily enough, if I go into dev tools and set the HTML height to 100%, it starts working properly - but then if I add that in the CSS it doesn't scroll again.

**Comment by ZachSaucier** [comment] 2020-04-16 18:41
@maximeDore's suggestion works for me in terms of the whole page scroll but the elements pinned on scroll are progressively more off the more you have on the page (i.e. the first one is only slightly off, the second is further off of where it should be, etc.).

**Comment by ZachSaucier** [comment] 2020-04-16 18:54
I was able to fix both the page not being able to be scrolled to the top and the pinning issue by using `setTimeout(() => window.dispatchEvent(new Event('resize')), 10);` after initializing Locomotive Scroll.

**Comment by freieradikale** [comment] 2020-04-17 10:37
I think we have to set the position for a container, which is moved with translate. "window" doesn't work here. The "el" is the object, which should be moved. I have the same issues with barba.js. The position doesn't match. At the moment i am using scroll.scrollTo(). But it is a smooth "locomotive" scroll, and not this, what we need.

**Comment by quentinhocde** [comment] 2020-06-01 14:45
Hello guys!

We had a `history.scrollRestoration = 'manual'` in the Smooth class, in this commit https://github.com/locomotivemtl/locomotive-scroll/commit/64977e131687c1e3e9609ddc08131fe20d5a7f01
I hope it will works!
It was released in `3.5.4` ✌️

Thanks

**Closed by quentinhocde** 2020-06-01 14:45 UTC

**Comment by spacedev75** [comment] 2021-01-13 01:47
Hi, I know this thread has 1 yo now but im still experiencing the same issue.
At first load smooth scroll is working fine (despite some height issues...) but as soon as I refresh the page smooth scroll just stop working and smooth class is not added. Any clue on this ?

Thanks

**Comment by freieradikale** [comment] 2021-01-13 09:25
Check this
https://ihatetomatoes.net/demos/barbajs/

**Comment by clairedornic** [comment] 2021-04-08 08:14
Hi, as spacedev75 i'm still experiencing the same issue.
I have an horizontal scroll and at first load, scroll is working fine but when I refresh the page the scroll is not working well. 
Someone know if the issue is fix and if it is, how it was fixed? 

Thanks
