### ISSUE TITLE
Event on Scroll Y sometimes 0

### ISSUE THREAD

**Issue by Enkirch** [locomotivemtl/locomotive-scroll#25] opened 2019-08-20 06:56 UTC
Hi, 
im using the on Scroll Event because i need the ScrollY Position. 

But it happens that sometimes pos Y becomes 0 during scrolling.

This is the Console.log

> {x: 0, y: 1427.0303071238382}
scripts.js?ver=1566283502:4157 {x: 0, y: 0}
scripts.js?ver=1566283502:4157 {x: 0, y: 1428.3272764114545}
scripts.js?ver=1566283502:4157 {x: 0, y: 0}
scripts.js?ver=1566283502:4157 {x: 0, y: 1429.4945487703092}
scripts.js?ver=1566283502:4157 {x: 0, y: 0}
scripts.js?ver=1566283502:4157 {x: 0, y: 1430.5450938932784}
scripts.js?ver=1566283502:4157 {x: 0, y: 0}
scripts.js?ver=1566283502:4157 {x: 0, y: 1431.4905845039505}
scripts.js?ver=1566283502:4157 {x: 0, y: 0}
scripts.js?ver=1566283502:4157 {x: 0, y: 1432.3415260535555}
scripts.js?ver=1566283502:4157 {x: 0, y: 0}
scripts.js?ver=1566283502:4157 {x: 0, y: 1433.1073734482}
scripts.js?ver=1566283502:4157 {x: 0, y: 0}
scripts.js?ver=1566283502:4157 {x: 0, y: 1433.79663610338}

This is my Code

> scroll = new LocomotiveScroll({
            el: document.querySelector('#js-scroll'),
            smooth: true,
            smoothMobile: true,
            inertia: 1,
            repeat: true
        }); 

> scroll.on("scroll", scrollOnScrolling);

>     function scrollOnScrolling(obj){
        var scrollY = obj["scroll"]["y"];
        //console.log("functiona");
        //console.log( obj );
        //console.log( obj[0] );
        //console.log( obj["direction"] );
        //console.log( obj["limit"] );
        //console.log( obj["speed"] );
        console.log( obj["scroll"] );

Any Ideas how this can happen. I need the Y Position because i want to add an Class if Scrolling is bigger 50, now with this 0 sometimes. It ends in addclass, removeclass, addclass, removeclass,....

**Comment by regenrek** [comment] 2019-08-23 20:48
Hey @Enkirch I needed something similiar recently. This is a working implementation with a `vuejs` mixin

But I can't tell you why you got sometimes 0 for y axis...

```js
import { mapActions, mapState } from "vuex";
import _ from "lodash";
const OFFSET = 350;

export default {
  data() {
    return {
      scrollPosition: 0
    };
  },
  mounted() {
    this.$nextTick(
      function() {
        this.lmS = new this.locomotiveScroll({
          el: document.querySelector("#js-scroll"),
          smooth: true /* if false disable overflow: hidden on html, body */
        });
        // @TODO: debounce not working?
        // const dd = _.debounce(this.onLmsScroll, 150);
        // this.lmS.on("scroll", dd);
        this.lmS.on("scroll", this.onLmsScroll);
      }.bind(this)
    );
  },
  computed: {
    ...mapState({
      navIsShrinked: state => state.nav.navIsShrinked
    })
  },
  methods: {
    onLmsScroll(obj) {
      this.scrollPosition = obj["scroll"]["y"];
      console.log(this.scrollPosition);
      if (this.scrollPosition < OFFSET) {
        if (this.navIsShrinked) {
          this.growNav();
          console.log("this.growNav();");
        }
      } else {
        if (!this.navIsShrinked) {
          this.shrinkNav();
          console.log("this.shrinkNav()");
        }
      }
    },
    ...mapActions({
      shrinkNav: "nav/shrinkNav",
      growNav: "nav/growNav"
    })
  }
};

```

**Comment by Jerek0** [comment] 2019-09-25 18:58
It seems the `y` value equals 0 once every 2 logs. Make sure you don't have multiple instances of Locomotive Scroll running at the same time?
Otherwise, please try to reproduce this issue in a codepen or similar so we can look at it further.

**Comment by quentinhocde** [comment] 2019-10-28 14:59
Hi!

We can't reproduce this issue.. We have no news, so we close it but if you still need help don't hesitate to tell us :)

**Closed by quentinhocde** 2019-10-28 14:59 UTC
